import type { QuizQuestion } from "@/lib/types/content";

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // Section A — SEO Fundamentals (5)
  {
    id: "q-a1",
    section: "A",
    skillId: "fundamentals",
    question: "Apa yang dimaksud dengan 'crawling' dalam SEO?",
    options: [
      "Proses Google menemukan dan membaca halaman website",
      "Proses membeli iklan di Google Ads",
      "Proses menyimpan halaman ke dalam index Google",
      "Proses mengurutkan halaman di hasil pencarian",
    ],
    correctIndex: 0,
    explanation: "Crawling adalah proses Googlebot menemukan dan membaca halaman website.",
  },
  {
    id: "q-a2",
    section: "A",
    skillId: "fundamentals",
    question: "Urutan tahapan yang benar dalam cara kerja mesin pencari adalah...",
    options: [
      "Ranking → Crawling → Indexing",
      "Indexing → Crawling → Ranking",
      "Crawling → Indexing → Ranking",
      "Crawling → Ranking → Indexing",
    ],
    correctIndex: 2,
    explanation: "Halaman harus di-crawl dulu, lalu di-index, baru bisa diranking.",
  },
  {
    id: "q-a3",
    section: "A",
    skillId: "fundamentals",
    question: "Manakah pernyataan yang BENAR tentang meta keywords?",
    options: [
      "Meta keywords adalah faktor ranking utama di Google",
      "Google sudah mengonfirmasi tidak menggunakan meta keywords untuk ranking",
      "Meta keywords wajib diisi minimal 10 kata",
      "Meta keywords menggantikan fungsi title tag",
    ],
    correctIndex: 1,
    explanation: "Google telah lama mengonfirmasi meta keywords tidak digunakan untuk ranking.",
  },
  {
    id: "q-a4",
    section: "A",
    skillId: "fundamentals",
    question: "Apa perbedaan utama antara SEO dan SEM?",
    options: [
      "SEO berbayar, SEM gratis",
      "SEO fokus organic traffic, SEM mencakup traffic berbayar seperti iklan",
      "SEO hanya untuk e-commerce, SEM untuk semua industri",
      "Tidak ada perbedaan, keduanya istilah yang sama",
    ],
    correctIndex: 1,
    explanation: "SEO berfokus pada organic traffic, sedangkan SEM mencakup strategi berbayar.",
  },
  {
    id: "q-a5",
    section: "A",
    skillId: "fundamentals",
    question: "Contoh praktik black hat SEO adalah...",
    options: [
      "Menulis title tag yang jelas dan relevan",
      "Membuat XML sitemap",
      "Keyword stuffing (menjejalkan keyword berlebihan)",
      "Memperbaiki kecepatan halaman",
    ],
    correctIndex: 2,
    explanation: "Keyword stuffing melanggar panduan Google dan termasuk praktik black hat.",
  },

  // Section B — Keyword & Search Intent (4)
  {
    id: "q-b1",
    section: "B",
    skillId: "keyword-research",
    question: "Keyword 'sepatu' vs 'sepatu lari trail wanita ukuran 38' — yang kedua disebut...",
    options: ["Short-tail keyword", "Long-tail keyword", "Branded keyword", "Navigational keyword"],
    correctIndex: 1,
    explanation: "Keyword yang panjang dan spesifik disebut long-tail keyword.",
  },
  {
    id: "q-b2",
    section: "B",
    skillId: "search-intent",
    question: "Query 'beli sepatu lari online' kemungkinan besar memiliki search intent...",
    options: ["Informational", "Navigational", "Commercial", "Transactional"],
    correctIndex: 3,
    explanation: "Kata 'beli' menandakan pengguna siap melakukan transaksi.",
  },
  {
    id: "q-b3",
    section: "B",
    skillId: "search-intent",
    question: "Cara tercepat untuk mengecek search intent sebuah keyword adalah...",
    options: [
      "Menebak berdasarkan panjang keyword",
      "Melihat langsung hasil 10 teratas di Google (SERP) untuk keyword tersebut",
      "Menanyakan ke tim marketing",
      "Melihat jumlah huruf dalam keyword",
    ],
    correctIndex: 1,
    explanation: "SERP adalah sumber paling akurat untuk memahami intent nyata di balik sebuah query.",
  },
  {
    id: "q-b4",
    section: "B",
    skillId: "keyword-research",
    question: "Apa tujuan utama membuat keyword map?",
    options: [
      "Agar semua keyword ditargetkan di satu halaman saja",
      "Memetakan keyword ke halaman yang tepat agar tidak saling bersaing",
      "Menghitung total kata dalam website",
      "Mengganti kebutuhan riset SERP",
    ],
    correctIndex: 1,
    explanation: "Keyword map mencegah keyword cannibalization dengan memberi setiap halaman fokus yang jelas.",
  },

  // Section C — On-Page SEO (4)
  {
    id: "q-c1",
    section: "C",
    skillId: "on-page-seo",
    question: "Elemen on-page yang paling berpengaruh terhadap klik di hasil pencarian adalah...",
    options: ["Title tag", "Warna background halaman", "Jumlah gambar", "Nama domain"],
    correctIndex: 0,
    explanation: "Title tag adalah elemen utama yang dilihat pengguna sebelum memutuskan klik.",
  },
  {
    id: "q-c2",
    section: "C",
    skillId: "on-page-seo",
    question: "Meta description berfungsi untuk...",
    options: [
      "Faktor ranking langsung terkuat",
      "Mempengaruhi CTR meski bukan faktor ranking langsung",
      "Mengganti fungsi H1",
      "Memblokir crawler",
    ],
    correctIndex: 1,
    explanation: "Meta description mempengaruhi keputusan klik pengguna, bukan ranking secara langsung.",
  },
  {
    id: "q-c3",
    section: "C",
    skillId: "on-page-seo",
    question: "Praktik heading yang benar untuk satu halaman adalah...",
    options: [
      "Menggunakan banyak H1 agar terlihat penting",
      "Satu H1 utama, lalu H2/H3 untuk sub-topik",
      "Semua teks menggunakan H1",
      "Heading tidak berpengaruh sama sekali, bisa diabaikan",
    ],
    correctIndex: 1,
    explanation: "Struktur heading yang jelas membantu pengguna dan mesin pencari memahami konten.",
  },
  {
    id: "q-c4",
    section: "C",
    skillId: "on-page-seo",
    question: "Contoh anchor text internal link yang BAIK adalah...",
    options: [
      "'klik di sini'",
      "'baca selengkapnya'",
      "'panduan lengkap riset keyword'",
      "URL mentah tanpa teks",
    ],
    correctIndex: 2,
    explanation: "Anchor text deskriptif membantu pengguna dan mesin pencari memahami halaman tujuan.",
  },

  // Section D — Technical SEO Basics (4)
  {
    id: "q-d1",
    section: "D",
    skillId: "technical-seo",
    question: "File robots.txt digunakan untuk...",
    options: [
      "Mengatur halaman mana yang boleh/tidak boleh di-crawl",
      "Mempercepat loading halaman",
      "Mengatur desain visual website",
      "Menyimpan data pengunjung",
    ],
    correctIndex: 0,
    explanation: "robots.txt memberi instruksi crawling ke bot mesin pencari.",
  },
  {
    id: "q-d2",
    section: "D",
    skillId: "technical-seo",
    question: "XML sitemap sebaiknya berisi...",
    options: [
      "Semua URL termasuk yang error dan redirect",
      "Hanya URL kanonis dengan status 200 yang ingin diindex",
      "Hanya halaman login",
      "Daftar keyword yang ditargetkan",
    ],
    correctIndex: 1,
    explanation: "Sitemap yang bersih hanya berisi halaman valid yang ingin diindex.",
  },
  {
    id: "q-d3",
    section: "D",
    skillId: "technical-seo",
    question: "Kode status HTTP 404 berarti...",
    options: [
      "Halaman berhasil diakses",
      "Halaman dipindahkan permanen",
      "Halaman tidak ditemukan",
      "Server sedang error",
    ],
    correctIndex: 2,
    explanation: "404 Not Found artinya halaman yang diminta tidak ditemukan.",
  },
  {
    id: "q-d4",
    section: "D",
    skillId: "technical-seo",
    question: "Laporan Coverage/Pages di Google Search Console berguna untuk...",
    options: [
      "Melihat halaman mana yang berhasil dan gagal diindex beserta alasannya",
      "Membeli iklan Google Ads",
      "Mengubah desain website",
      "Mengukur kecepatan internet pengguna",
    ],
    correctIndex: 0,
    explanation: "Laporan ini menunjukkan status indexing setiap halaman beserta penyebab kegagalannya.",
  },

  // Section E — Measurement Basics (3)
  {
    id: "q-e1",
    section: "E",
    skillId: "analytics",
    question: "CTR (Click-Through Rate) dihitung dari...",
    options: [
      "Clicks dibagi Impressions",
      "Impressions dibagi Clicks",
      "Jumlah halaman dibagi jumlah kata",
      "Posisi rata-rata dikali jumlah klik",
    ],
    correctIndex: 0,
    explanation: "CTR = jumlah klik dibagi jumlah impressions.",
  },
  {
    id: "q-e2",
    section: "E",
    skillId: "analytics",
    question: "Jika impressions naik tapi klik turun, kemungkinan penyebabnya adalah...",
    options: [
      "Website sedang down total",
      "Posisi ranking turun atau title/meta kurang menarik",
      "Google Analytics error",
      "Tidak ada penyebab yang masuk akal",
    ],
    correctIndex: 1,
    explanation: "Penurunan posisi atau title/meta yang kurang menarik bisa menurunkan klik meski impressions naik.",
  },
  {
    id: "q-e3",
    section: "E",
    skillId: "analytics",
    question: "Organic traffic di GA4 mengacu pada...",
    options: [
      "Pengunjung dari iklan berbayar",
      "Pengunjung dari hasil pencarian alami (bukan iklan)",
      "Pengunjung dari media sosial saja",
      "Pengunjung yang mengetik URL langsung",
    ],
    correctIndex: 1,
    explanation: "Organic traffic adalah trafik dari hasil pencarian alami, bukan iklan berbayar.",
  },
];
