import type { TaskTemplate } from "@/lib/types/content";

export const TASK_TEMPLATES: TaskTemplate[] = [
  // ---- Level 0 — Fundamentals (2) ----
  {
    id: "task-f1-indexing-check",
    levelId: "level-0-fundamentals",
    skillId: "fundamentals",
    title: "Cek Status Indexing Sebuah Website",
    objective:
      "Memverifikasi apakah sebuah website (dan halaman-halaman pentingnya) sudah ter-index oleh Google.",
    why: "Ini adalah pemeriksaan paling dasar yang akan kamu lakukan berulang kali sebagai SEO specialist — memastikan konten benar-benar bisa ditemukan.",
    instructions: [
      "Pilih satu website nyata (bisa milikmu sendiri, teman, atau bisnis kecil di sekitarmu).",
      "Gunakan pencarian 'site:domainkamu.com' di Google untuk melihat halaman yang ter-index.",
      "Bandingkan jumlah halaman yang muncul dengan perkiraan jumlah halaman sebenarnya di website tersebut.",
      "Catat 2-3 halaman penting dan cek apakah masing-masing muncul di hasil site: search.",
    ],
    estMinutes: 30,
    tools: ["Google Search"],
    expectedOutput: "Catatan singkat berisi jumlah halaman ter-index dan halaman mana yang tampak hilang.",
    evidenceType: "text",
    rubric: [
      "Menyebutkan website yang diaudit dan hasil pencarian site:",
      "Menyebutkan minimal 2 halaman penting yang dicek satu per satu",
      "Ada kesimpulan singkat apakah indexing website ini sehat atau bermasalah",
    ],
    portfolioEligible: false,
  },
  {
    id: "task-f2-organic-vs-ads",
    levelId: "level-0-fundamentals",
    skillId: "fundamentals",
    title: "Bandingkan Hasil Organic vs Iklan di SERP",
    objective: "Membedakan secara visual antara hasil pencarian organic dan iklan berbayar.",
    why: "Kemampuan mengenali elemen SERP dengan cepat adalah dasar sebelum melakukan riset keyword atau analisis kompetitor.",
    instructions: [
      "Cari satu keyword yang bersifat komersial (contoh: 'jasa desain logo' atau 'beli laptop bekas').",
      "Screenshot atau catat halaman hasil pencarian pertama.",
      "Tandai mana saja yang merupakan iklan (biasanya berlabel 'Sponsored' atau 'Iklan') dan mana yang organic.",
      "Catat pengamatanmu tentang perbedaan judul dan format antara keduanya.",
    ],
    estMinutes: 20,
    tools: ["Google Search"],
    expectedOutput: "Catatan atau screenshot dengan penandaan iklan vs organic.",
    evidenceType: "both",
    rubric: [
      "Keyword yang dipilih bersifat komersial",
      "Berhasil membedakan iklan dan hasil organic dengan benar",
      "Ada catatan pengamatan tentang perbedaan formatnya",
    ],
    portfolioEligible: false,
  },

  // ---- Level 1 — Keyword & Search Intent (4) ----
  {
    id: "task-k1-classify-intent",
    levelId: "level-1-keyword",
    skillId: "search-intent",
    title: "Klasifikasikan Search Intent 15 Keyword",
    objective: "Melatih kemampuan mengenali 4 jenis search intent secara cepat dan akurat.",
    why: "Salah menargetkan intent adalah penyebab paling umum konten tidak pernah ranking meski sudah dioptimasi.",
    instructions: [
      "Kumpulkan 15 keyword dari satu topik/niche yang kamu pilih.",
      "Untuk masing-masing keyword, cek SERP di Google untuk memastikan intent-nya.",
      "Klasifikasikan setiap keyword ke salah satu dari 4 jenis intent: informational, navigational, commercial, transactional.",
      "Susun hasilnya dalam bentuk tabel sederhana.",
    ],
    estMinutes: 45,
    tools: ["Google Search", "Spreadsheet (Google Sheets/Excel)"],
    expectedOutput: "Tabel 15 keyword lengkap dengan klasifikasi intent dan alasan singkat.",
    evidenceType: "both",
    rubric: [
      "15 keyword terklasifikasi dengan salah satu dari 4 jenis intent",
      "Setiap klasifikasi didukung dengan bukti dari SERP, bukan tebakan",
      "Format rapi dan mudah dibaca (tabel)",
    ],
    portfolioEligible: false,
  },
  {
    id: "task-k2-serp-analysis",
    levelId: "level-1-keyword",
    skillId: "search-intent",
    title: "Analisis SERP untuk 5 Keyword Target",
    objective: "Memahami apa yang membuat halaman-halaman teratas berhasil ranking untuk keyword tertentu.",
    why: "Analisis SERP membantu menentukan format dan sudut pandang konten yang paling relevan sebelum mulai menulis.",
    instructions: [
      "Pilih 5 keyword yang relevan dengan satu niche/bisnis.",
      "Untuk setiap keyword, buka 10 hasil teratas dan catat: jenis konten (artikel/produk/kategori), panjang konten perkiraan, dan format (list, panduan, review, dll).",
      "Simpulkan pola umum yang muncul di setiap keyword.",
    ],
    estMinutes: 40,
    tools: ["Google Search", "Spreadsheet"],
    expectedOutput: "Ringkasan pola SERP untuk 5 keyword beserta rekomendasi format konten.",
    evidenceType: "both",
    rubric: [
      "5 keyword dianalisis dengan data dari 10 hasil teratas masing-masing",
      "Pola/kesamaan format konten teridentifikasi dengan jelas",
      "Ada rekomendasi format konten berdasarkan hasil analisis",
    ],
    portfolioEligible: false,
  },
  {
    id: "task-k3-keyword-clustering",
    levelId: "level-1-keyword",
    skillId: "keyword-research",
    title: "Riset dan Kelompokkan 20 Keyword",
    objective: "Melakukan riset keyword dasar dan mengelompokkannya berdasarkan kemiripan topik/intent.",
    why: "Pengelompokan keyword yang baik adalah fondasi sebelum menyusun keyword map dan strategi konten.",
    instructions: [
      "Pilih satu topik/niche bisnis.",
      "Kumpulkan minimal 20 keyword terkait menggunakan Google Suggest, People Also Ask, dan Related Searches.",
      "Kelompokkan keyword ke dalam 4-6 cluster berdasarkan kemiripan topik.",
      "Beri nama setiap cluster yang mencerminkan temanya.",
    ],
    estMinutes: 45,
    tools: ["Google Search", "Spreadsheet"],
    expectedOutput: "Daftar 20+ keyword yang sudah dikelompokkan ke dalam cluster bertema.",
    evidenceType: "both",
    rubric: [
      "Minimal 20 keyword terkumpul dan relevan dengan niche",
      "Keyword terkelompok ke cluster yang masuk akal",
      "Setiap cluster punya nama yang jelas",
    ],
    portfolioEligible: false,
  },
  {
    id: "task-k4-keyword-map-project",
    levelId: "level-1-keyword",
    skillId: "keyword-research",
    title: "Project: Keyword Map",
    objective:
      "Menyusun keyword map lengkap yang memetakan keyword ke halaman spesifik untuk satu website/niche.",
    why: "Ini adalah project utama Level 1 dan bukti kerja nyata pertama yang bisa masuk ke portofolio.",
    instructions: [
      "Gunakan hasil riset dan pengelompokan keyword dari tugas sebelumnya (atau mulai baru bila belum).",
      "Untuk setiap cluster keyword, tentukan satu halaman target (halaman existing atau ide halaman baru).",
      "Sertakan kolom: keyword utama, keyword pendukung, intent, halaman target, prioritas.",
      "Pastikan tidak ada dua halaman yang menargetkan cluster keyword yang sama (hindari cannibalization).",
    ],
    estMinutes: 60,
    tools: ["Spreadsheet (Google Sheets/Excel)", "Google Search"],
    expectedOutput: "Dokumen Keyword Map lengkap (spreadsheet) yang siap dipakai untuk perencanaan konten.",
    evidenceType: "both",
    rubric: [
      "Setiap cluster keyword punya satu halaman target yang jelas",
      "Search intent tercantum untuk setiap baris",
      "Prioritas ditentukan dengan alasan yang masuk akal",
      "Tidak ada tumpang tindih target antar halaman",
    ],
    portfolioEligible: true,
  },

  // ---- Level 2 — On-Page SEO (4) ----
  {
    id: "task-o1-internal-link-audit",
    levelId: "level-2-onpage",
    skillId: "on-page-seo",
    title: "Audit Internal Link 1 Halaman",
    objective: "Mengevaluasi kualitas internal linking pada satu halaman penting.",
    why: "Internal linking yang buruk membuat halaman penting sulit ditemukan oleh Google maupun pengguna.",
    instructions: [
      "Pilih satu halaman penting dari website pilihanmu.",
      "Catat semua internal link yang ada di halaman tersebut beserta anchor text-nya.",
      "Identifikasi anchor text yang kurang deskriptif (contoh: 'klik di sini').",
      "Berikan minimal 3 rekomendasi perbaikan internal linking.",
    ],
    estMinutes: 30,
    tools: ["Browser (View Page Source / Inspect Element)"],
    expectedOutput: "Daftar internal link halaman beserta evaluasi dan rekomendasi perbaikan.",
    evidenceType: "both",
    rubric: [
      "Semua internal link di halaman tercatat",
      "Anchor text yang buruk teridentifikasi dengan jelas",
      "Minimal 3 rekomendasi perbaikan yang konkret",
    ],
    portfolioEligible: false,
  },
  {
    id: "task-o2-heading-audit",
    levelId: "level-2-onpage",
    skillId: "on-page-seo",
    title: "Evaluasi Struktur Heading 3 Halaman",
    objective: "Memeriksa apakah struktur H1-H3 pada beberapa halaman sudah sesuai praktik yang baik.",
    why: "Struktur heading yang berantakan membingungkan pengguna dan mempersulit mesin pencari memahami isi halaman.",
    instructions: [
      "Pilih 3 halaman dari website yang sama atau berbeda.",
      "Catat seluruh heading (H1, H2, H3) di setiap halaman beserta urutannya.",
      "Tandai masalah yang ditemukan: H1 ganda, heading yang loncat urutan, atau heading yang hanya untuk styling.",
      "Berikan rekomendasi struktur heading yang lebih baik untuk minimal 1 halaman.",
    ],
    estMinutes: 30,
    tools: ["Browser (Inspect Element)"],
    expectedOutput: "Catatan struktur heading 3 halaman beserta temuan masalah dan rekomendasi.",
    evidenceType: "both",
    rubric: [
      "Struktur heading 3 halaman tercatat lengkap",
      "Masalah struktur (jika ada) teridentifikasi dengan jelas",
      "Ada rekomendasi perbaikan yang konkret",
    ],
    portfolioEligible: false,
  },
  {
    id: "task-o3-content-brief",
    levelId: "level-2-onpage",
    skillId: "content-seo",
    title: "Build Content Brief untuk 1 Topik",
    objective: "Menyusun content brief yang selaras dengan search intent untuk membantu penulisan konten.",
    why: "Content brief adalah jembatan antara riset keyword/intent dan eksekusi konten yang efektif.",
    instructions: [
      "Pilih satu keyword target dari hasil riset sebelumnya.",
      "Analisis SERP untuk keyword tersebut dan tentukan search intent-nya.",
      "Susun brief berisi: judul rekomendasi, search intent, target audiens, poin-poin yang wajib dibahas, dan keyword pendukung.",
    ],
    estMinutes: 35,
    tools: ["Google Search", "Dokumen teks"],
    expectedOutput: "Satu dokumen content brief siap dipakai untuk menulis artikel/halaman.",
    evidenceType: "text",
    rubric: [
      "Search intent teridentifikasi dengan benar dari analisis SERP",
      "Poin-poin konten yang wajib dibahas relevan dan cukup lengkap",
      "Brief bisa langsung dipakai untuk mulai menulis tanpa riset ulang",
    ],
    portfolioEligible: false,
  },
  {
    id: "task-o4-optimize-3-pages-project",
    levelId: "level-2-onpage",
    skillId: "on-page-seo",
    title: "Project: Optimize 3 Pages",
    objective:
      "Mengoptimalkan title tag, meta description, dan struktur heading untuk 3 halaman nyata.",
    why: "Ini adalah project utama Level 2 dan menunjukkan kemampuan on-page SEO secara end-to-end.",
    instructions: [
      "Pilih 3 halaman nyata yang membutuhkan optimasi (boleh dari website sendiri atau website lain dengan izin/tujuan latihan).",
      "Untuk setiap halaman, tuliskan versi 'sebelum' (title, meta description, H1 saat ini).",
      "Tuliskan versi 'sesudah' hasil optimasimu beserta alasan setiap perubahan.",
      "Jelaskan keyword/intent yang menjadi dasar setiap keputusan optimasi.",
    ],
    estMinutes: 60,
    tools: ["Browser", "Google Search", "Dokumen teks"],
    expectedOutput: "Dokumen perbandingan before/after untuk 3 halaman lengkap dengan alasan setiap perubahan.",
    evidenceType: "both",
    rubric: [
      "3 halaman punya versi before/after yang jelas",
      "Setiap perubahan title/meta/H1 disertai alasan yang berbasis keyword atau intent",
      "Panjang title dan meta description sudah wajar (tidak terpotong)",
    ],
    portfolioEligible: true,
  },

  // ---- Level 3-Lite — Technical SEO Basics (4) ----
  {
    id: "task-t1-robots-check",
    levelId: "level-3-technical",
    skillId: "technical-seo",
    title: "Cek dan Analisis robots.txt Website",
    objective: "Membaca dan mengevaluasi isi file robots.txt sebuah website.",
    why: "Kesalahan konfigurasi robots.txt bisa memblokir seluruh website dari hasil pencarian tanpa disadari.",
    instructions: [
      "Buka domainkamu.com/robots.txt untuk website pilihanmu.",
      "Catat aturan Disallow/Allow yang ada beserta user-agent yang ditargetkan.",
      "Periksa apakah ada aturan yang secara tidak sengaja memblokir halaman penting.",
      "Cek apakah ada baris 'Sitemap:' di dalamnya.",
    ],
    estMinutes: 25,
    tools: ["Browser"],
    expectedOutput: "Ringkasan isi robots.txt beserta temuan potensi masalah.",
    evidenceType: "text",
    rubric: [
      "Isi robots.txt dicatat dengan akurat",
      "Ada evaluasi apakah ada halaman penting yang berisiko terblokir",
      "Disebutkan apakah baris Sitemap ada atau tidak",
    ],
    portfolioEligible: false,
  },
  {
    id: "task-t2-sitemap-check",
    levelId: "level-3-technical",
    skillId: "technical-seo",
    title: "Cek dan Evaluasi XML Sitemap",
    objective: "Memverifikasi keberadaan dan kualitas XML sitemap sebuah website.",
    why: "Sitemap yang bersih membantu Google menemukan halaman penting lebih cepat.",
    instructions: [
      "Coba akses domainkamu.com/sitemap.xml (atau cari lokasi sitemap dari robots.txt).",
      "Catat jumlah URL yang terdaftar di sitemap.",
      "Cek beberapa sample URL — apakah semuanya valid (status 200) dan relevan untuk diindex.",
      "Simpulkan apakah sitemap ini sehat atau perlu diperbaiki.",
    ],
    estMinutes: 25,
    tools: ["Browser"],
    expectedOutput: "Ringkasan evaluasi sitemap beserta kesimpulan kesehatannya.",
    evidenceType: "text",
    rubric: [
      "Keberadaan dan lokasi sitemap terkonfirmasi",
      "Sample URL dari sitemap dicek validitasnya",
      "Ada kesimpulan yang jelas tentang kesehatan sitemap",
    ],
    portfolioEligible: false,
  },
  {
    id: "task-t3-status-code-audit",
    levelId: "level-3-technical",
    skillId: "technical-seo",
    title: "Audit HTTP Status Code Halaman Penting",
    objective: "Memeriksa status code dari beberapa halaman dan link penting di sebuah website.",
    why: "Link yang mengarah ke halaman 404 atau redirect berantai merugikan pengalaman pengguna dan crawl budget.",
    instructions: [
      "Pilih 8-10 URL penting dari sebuah website (halaman utama, kategori, beberapa link internal).",
      "Cek status code masing-masing menggunakan tool pengecekan status HTTP (misalnya fitur developer tools browser atau tool online status checker).",
      "Catat mana yang 200, redirect (301/302), atau error (404/5xx).",
      "Berikan rekomendasi untuk setiap URL yang bermasalah.",
    ],
    estMinutes: 35,
    tools: ["Browser Developer Tools", "HTTP status checker online"],
    expectedOutput: "Tabel status code untuk 8-10 URL beserta rekomendasi perbaikan.",
    evidenceType: "both",
    rubric: [
      "8-10 URL dicek dan dicatat status code-nya",
      "URL bermasalah (404/redirect berantai) teridentifikasi",
      "Ada rekomendasi untuk setiap masalah yang ditemukan",
    ],
    portfolioEligible: false,
  },
  {
    id: "task-t4-gsc-coverage-audit",
    levelId: "level-3-technical",
    skillId: "technical-seo",
    title: "Audit Index Coverage via Search Console",
    objective: "Membaca laporan Pages/Coverage di Google Search Console untuk mendiagnosis masalah indexing.",
    why: "Ini adalah skill inti technical SEO yang hampir selalu ditanyakan saat interview.",
    instructions: [
      "Akses Google Search Console untuk sebuah properti (milikmu sendiri, atau gunakan akun demo/latihan bila belum punya properti).",
      "Buka laporan Pages (Coverage) dan catat jumlah halaman yang 'Indexed' vs 'Not indexed'.",
      "Pilih 2-3 alasan 'Not indexed' yang muncul dan jelaskan artinya.",
      "Jika belum punya akses GSC, boleh gunakan screenshot contoh dari dokumentasi resmi Google sebagai bahan latihan membaca laporan, dan jelaskan cara membacanya.",
    ],
    estMinutes: 30,
    tools: ["Google Search Console"],
    expectedOutput: "Ringkasan status coverage beserta penjelasan alasan halaman tidak terindex.",
    evidenceType: "text",
    rubric: [
      "Jumlah halaman indexed vs not indexed disebutkan",
      "Minimal 2 alasan 'not indexed' dijelaskan dengan benar",
      "Ada pemahaman yang jelas tentang cara membaca laporan ini",
    ],
    portfolioEligible: false,
  },

  // ---- Level 5-Lite — Measurement Basics (3) ----
  {
    id: "task-m1-gsc-performance",
    levelId: "level-5-measurement",
    skillId: "analytics",
    title: "Analisis Data Performa GSC",
    objective: "Membaca dan menganalisis data impressions, clicks, CTR, dan posisi dari Search Console.",
    why: "Data performa GSC adalah sumber utama untuk mengevaluasi efektivitas strategi SEO.",
    instructions: [
      "Buka laporan Performance di Google Search Console untuk sebuah properti (atau gunakan data contoh/demo bila belum punya akses).",
      "Catat total impressions, clicks, CTR rata-rata, dan posisi rata-rata dalam 28 hari terakhir.",
      "Identifikasi 3 query dengan impressions tinggi tapi CTR rendah.",
      "Berikan hipotesis kenapa CTR-nya rendah untuk masing-masing query.",
    ],
    estMinutes: 30,
    tools: ["Google Search Console"],
    expectedOutput: "Ringkasan metrik performa beserta 3 query bermasalah dan hipotesis penyebabnya.",
    evidenceType: "text",
    rubric: [
      "4 metrik utama (impressions, clicks, CTR, posisi) tercatat",
      "3 query dengan CTR rendah teridentifikasi dengan data pendukung",
      "Hipotesis penyebab CTR rendah masuk akal dan berbasis title/meta/posisi",
    ],
    portfolioEligible: false,
  },
  {
    id: "task-m2-ga4-traffic",
    levelId: "level-5-measurement",
    skillId: "analytics",
    title: "Analisis Organic Traffic di GA4",
    objective: "Membaca laporan traffic acquisition di GA4 untuk memahami kontribusi organic search.",
    why: "Menghubungkan data GSC dengan GA4 memberi gambaran lengkap dari klik hingga perilaku pengguna di halaman.",
    instructions: [
      "Buka laporan Traffic Acquisition di GA4 untuk sebuah properti (atau gunakan akun demo GA4 milik Google bila belum punya akses).",
      "Catat persentase traffic dari 'Organic Search' dibanding sumber lain.",
      "Catat engagement rate untuk trafik organic.",
      "Simpulkan apakah organic search adalah sumber trafik yang signifikan untuk website tersebut.",
    ],
    estMinutes: 30,
    tools: ["Google Analytics 4"],
    expectedOutput: "Ringkasan kontribusi organic traffic beserta engagement rate-nya.",
    evidenceType: "text",
    rubric: [
      "Persentase kontribusi organic search tercatat",
      "Engagement rate organic traffic tercatat",
      "Ada kesimpulan yang jelas tentang signifikansi organic search",
    ],
    portfolioEligible: false,
  },
  {
    id: "task-m3-gsc-ga4-insight",
    levelId: "level-5-measurement",
    skillId: "analytics",
    title: "Susun Insight Gabungan dari GSC + GA4",
    objective: "Menggabungkan data dari dua sumber untuk menghasilkan satu insight dan rekomendasi.",
    why: "Kemampuan menggabungkan data dari berbagai sumber menjadi rekomendasi adalah inti dari peran SEO strategist.",
    instructions: [
      "Gunakan data dari 2 tugas sebelumnya (GSC Performance dan GA4 Traffic).",
      "Temukan satu masalah yang terlihat di kedua data (contoh: klik tinggi dari GSC tapi engagement rendah di GA4).",
      "Tuliskan satu insight singkat dan satu rekomendasi tindakan berdasarkan insight tersebut.",
    ],
    estMinutes: 25,
    tools: ["Google Search Console", "Google Analytics 4"],
    expectedOutput: "Satu insight tertulis beserta satu rekomendasi tindakan yang konkret.",
    evidenceType: "text",
    rubric: [
      "Insight menghubungkan data dari GSC dan GA4, bukan hanya salah satu",
      "Rekomendasi bersifat konkret dan bisa langsung dieksekusi",
    ],
    portfolioEligible: false,
  },

  // ---- Capstone (1) ----
  {
    id: "task-cap-full-audit",
    levelId: "capstone",
    skillId: "seo-strategy",
    title: "Project: Full SEO Audit",
    objective:
      "Menyusun satu SEO audit end-to-end untuk satu website nyata, mencakup fundamentals, keyword, on-page, technical, dan measurement.",
    why: "Ini adalah bukti kerja utama (capstone) yang menunjukkan kemampuanmu secara menyeluruh kepada calon employer.",
    instructions: [
      "Pilih satu website nyata (idealnya website kecil/UMKM yang butuh bantuan SEO — bisa juga website latihan).",
      "Audit status indexing dan technical SEO dasar (robots.txt, sitemap, status code, coverage).",
      "Audit on-page SEO untuk 3-5 halaman penting (title, meta, heading, internal link).",
      "Lakukan riset keyword singkat untuk merekomendasikan peluang konten baru.",
      "Jika memungkinkan, sertakan data performa dari GSC/GA4.",
      "Susun semua temuan menjadi satu dokumen audit dengan struktur: ringkasan masalah, temuan detail, dan rekomendasi prioritas.",
    ],
    estMinutes: 180,
    tools: [
      "Google Search",
      "Browser Developer Tools",
      "Google Search Console",
      "Google Analytics 4",
      "Spreadsheet/Dokumen",
    ],
    expectedOutput:
      "Satu dokumen SEO audit lengkap yang siap dipresentasikan ke pemilik bisnis atau ditunjukkan ke calon employer.",
    evidenceType: "both",
    rubric: [
      "Mencakup temuan technical, on-page, keyword, dan (bila tersedia) measurement",
      "Setiap temuan disertai rekomendasi yang konkret dan bisa dieksekusi",
      "Ada prioritas yang jelas — mana yang harus dikerjakan lebih dulu",
      "Dokumen tersusun rapi dan bisa dipahami oleh orang non-teknis (misal pemilik bisnis)",
    ],
    portfolioEligible: true,
  },
];
